### ISSUE TITLE
Author and Author email is not get parsed in the pypi json

### ISSUE THREAD

**Issue by rizahmeds** [neuro-ml/tarn#24]
[https://pypi.org/pypi/tarn/json](https://pypi.org/pypi/tarn/json)
<img width="634" alt="Screenshot 2023-05-26 at 18 15 24" src="https://github.com/neuro-ml/tarn/assets/109952697/811b65c1-38db-4548-962f-2398768dffca">

Author name and email is not visible.

**Comment by maxme1** [comment]
Hmm, that's strange. We'll release a fix by the end of the week

**Comment by maxme1** [comment]
Hey @rizahmeds Now it should be fixed. Feel free to open a new issue if you have any more problems
